// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhlegmaticOne.InnoGotchi.Data.EntityFramework.Context;

#nullable disable

namespace PhlegmaticOne.InnoGotchi.Data.EntityFramework.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221108111204_avatar-entity-created")]
    partial class avatarentitycreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.Avatar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("AvatarData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("Avatar");
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.Collaboration", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserProfileId", "FarmId");

                    b.HasIndex("FarmId");

                    b.ToTable("Collaborations", (string)null);
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.Farm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Farms", (string)null);
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.InnoGotchiComponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InnoGotchiComponents", (string)null);
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.InnoGotchiModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FarmId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HungerLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Normal");

                    b.Property<DateTime>("LastDrinkTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastFeedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ThirstyLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Normal");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("InnoGotchies", (string)null);
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.InnoGotchiModelComponent", b =>
                {
                    b.Property<Guid>("InnoGotchiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ComponentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<float>("ScaleX")
                        .HasColumnType("real");

                    b.Property<float>("ScaleY")
                        .HasColumnType("real");

                    b.Property<float>("TranslationX")
                        .HasColumnType("real");

                    b.Property<float>("TranslationY")
                        .HasColumnType("real");

                    b.HasKey("InnoGotchiId", "ComponentId");

                    b.HasIndex("ComponentId");

                    b.ToTable("InnoGotchiModelComponents", (string)null);
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("InvitationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ToProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FromProfileId");

                    b.HasIndex("ToProfileId");

                    b.ToTable("Invitations", (string)null);
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.Avatar", b =>
                {
                    b.HasOne("PhlegmaticOne.InnoGotchi.Data.Models.UserProfile", "UserProfile")
                        .WithOne("Avatar")
                        .HasForeignKey("PhlegmaticOne.InnoGotchi.Data.Models.Avatar", "UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.Collaboration", b =>
                {
                    b.HasOne("PhlegmaticOne.InnoGotchi.Data.Models.Farm", "Farm")
                        .WithMany("Collaborations")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhlegmaticOne.InnoGotchi.Data.Models.UserProfile", "Collaborator")
                        .WithMany("Collaborations")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Collaborator");

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.Farm", b =>
                {
                    b.HasOne("PhlegmaticOne.InnoGotchi.Data.Models.UserProfile", "Owner")
                        .WithOne("Farm")
                        .HasForeignKey("PhlegmaticOne.InnoGotchi.Data.Models.Farm", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.InnoGotchiModel", b =>
                {
                    b.HasOne("PhlegmaticOne.InnoGotchi.Data.Models.Farm", "Farm")
                        .WithMany("InnoGotchies")
                        .HasForeignKey("FarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.InnoGotchiModelComponent", b =>
                {
                    b.HasOne("PhlegmaticOne.InnoGotchi.Data.Models.InnoGotchiComponent", "InnoGotchiComponent")
                        .WithMany("InnoGotchiModelComponents")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PhlegmaticOne.InnoGotchi.Data.Models.InnoGotchiModel", "InnoGotchi")
                        .WithMany("Components")
                        .HasForeignKey("InnoGotchiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InnoGotchi");

                    b.Navigation("InnoGotchiComponent");
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.Invitation", b =>
                {
                    b.HasOne("PhlegmaticOne.InnoGotchi.Data.Models.UserProfile", "From")
                        .WithMany("SentInvitations")
                        .HasForeignKey("FromProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PhlegmaticOne.InnoGotchi.Data.Models.UserProfile", "To")
                        .WithMany("ReceivedInvitations")
                        .HasForeignKey("ToProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("From");

                    b.Navigation("To");
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.UserProfile", b =>
                {
                    b.HasOne("PhlegmaticOne.InnoGotchi.Data.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("PhlegmaticOne.InnoGotchi.Data.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.Farm", b =>
                {
                    b.Navigation("Collaborations");

                    b.Navigation("InnoGotchies");
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.InnoGotchiComponent", b =>
                {
                    b.Navigation("InnoGotchiModelComponents");
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.InnoGotchiModel", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.User", b =>
                {
                    b.Navigation("Profile")
                        .IsRequired();
                });

            modelBuilder.Entity("PhlegmaticOne.InnoGotchi.Data.Models.UserProfile", b =>
                {
                    b.Navigation("Avatar")
                        .IsRequired();

                    b.Navigation("Collaborations");

                    b.Navigation("Farm")
                        .IsRequired();

                    b.Navigation("ReceivedInvitations");

                    b.Navigation("SentInvitations");
                });
#pragma warning restore 612, 618
        }
    }
}
